-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [Adress]
CREATE TABLE [Adress]
(
 [adressID]   int NOT NULL ,
 [country]    varchar(64) NOT NULL ,
 [city]       varchar(64) NOT NULL ,
 [postalCode] int NOT NULL ,
 [street]     varchar(64) NOT NULL ,
 [houseNr]    int NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([adressID] ASC)
);
GO
