-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


IF NOT EXISTS (SELECT * FROM sys.schemas s WHERE s.name='group7')
EXEC ('CREATE SCHEMA [group7]');
GO

-- ************************************** [allocationType]
IF NOT EXISTS (SELECT * FROM sys.tables t WHERE t.name='allocationType')
CREATE TABLE [allocationType]
(
 [allocationTypeID]   int NOT NULL ,
 [allocationTypeName] varchar(64) NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([allocationTypeID] ASC)
);
GO
