-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [allocationType]
CREATE TABLE [allocationType]
(
 [allocationTypeID]   int NOT NULL ,
 [allocationTypeName] varchar(64) NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([allocationTypeID] ASC)
);
GO
