-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


IF NOT EXISTS (SELECT * FROM sys.schemas s WHERE s.name='group7')
EXEC ('CREATE SCHEMA [group7]');
GO

-- ************************************** [Contract]
IF NOT EXISTS (SELECT * FROM sys.tables t WHERE t.name='Contract' AND t.schema_id IN ( SELECT schema_id  FROM sys.schemas s WHERE s.name='group7') )
CREATE TABLE [group7].[Contract]
(
 [contractID]  int NOT NULL ,
 [nrResidents] int NOT NULL ,
 [tenantID]    int NOT NULL ,
 [unitID]      int NOT NULL ,
 [ownerID]     int NOT NULL ,
 [warmRent]    int NOT NULL ,
 [startDate]   datetime NOT NULL ,
 [endDate]     datetime NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([contractID] ASC),
 CONSTRAINT [FK_5] FOREIGN KEY ([ownerID])  REFERENCES [Owner]([ownerID]),
 CONSTRAINT [FK_6] FOREIGN KEY ([unitID])  REFERENCES [Unit]([unitID]),
 CONSTRAINT [FK_7] FOREIGN KEY ([tenantID])  REFERENCES [Tenant]([tenantID])
);
GO


CREATE NONCLUSTERED INDEX [FK_2] ON [Contract] 
 (
  [ownerID] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_3] ON [Contract] 
 (
  [unitID] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_4] ON [Contract] 
 (
  [tenantID] ASC
 )

GO
