-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [Manager]
CREATE TABLE [Manager]
(
 [managerID] int NOT NULL ,
 [firstName] varchar(64) NOT NULL ,
 [lastName]  varchar(64) NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([managerID] ASC)
);
GO
