-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [Owner]
CREATE TABLE [Owner]
(
 [ownerID]     int NOT NULL ,
 [firstName]   varchar(64) NOT NULL ,
 [lastName]    varchar(64) NOT NULL ,
 [bankAccount] varchar(255) NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([ownerID] ASC)
);
GO
