-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


IF NOT EXISTS (SELECT * FROM sys.schemas s WHERE s.name='group7')
EXEC ('CREATE SCHEMA [group7]');
GO

-- ************************************** [Payment]
IF NOT EXISTS (SELECT * FROM sys.tables t WHERE t.name='Payment' AND t.schema_id IN ( SELECT schema_id  FROM sys.schemas s WHERE s.name='group7'))
CREATE TABLE [group7].[Payment]
(
 [paymentID] int IDENTITY(1,1) PRIMARY KEY ,
 [tenantID]  int NOT NULL ,
 [amount]    int NOT NULL ,
 [unitID]    int NOT NULL ,
 [date]      datetime NOT NULL ,


 CONSTRAINT [FK_13] FOREIGN KEY ([unitID])  REFERENCES [group7].[Unit]([unitID]),
 CONSTRAINT [FK_14] FOREIGN KEY ([tenantID])  REFERENCES [group7].[Tenant]([tenantID])
);
GO