-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [Payment]
CREATE TABLE [Payment]
(
 [paymentID] int NOT NULL ,
 [tenantID]  int NOT NULL ,
 [amount]    int NOT NULL ,
 [unitID]    int NOT NULL ,
 [date]      datetime NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([paymentID] ASC),
 CONSTRAINT [FK_13] FOREIGN KEY ([unitID])  REFERENCES [Unit]([unitID]),
 CONSTRAINT [FK_14] FOREIGN KEY ([tenantID])  REFERENCES [Tenant]([tenantID])
);
GO


CREATE NONCLUSTERED INDEX [FK_2] ON [Payment] 
 (
  [unitID] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_3] ON [Payment] 
 (
  [tenantID] ASC
 )

GO
