-- Warning: You can generate script only for one table/view at a time in your Free plan 
-- 
-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [Position]
CREATE TABLE [Position]
(
 [positionID]       int NOT NULL ,
 [positionName]     varchar(255) NOT NULL ,
 [allocationTypeID] int NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([positionID] ASC),
 CONSTRAINT [FK_12] FOREIGN KEY ([allocationTypeID])  REFERENCES [allocationType]([allocationTypeID])
);
GO


CREATE NONCLUSTERED INDEX [FK_2] ON [Position] 
 (
  [allocationTypeID] ASC
 )

GO
