-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


IF NOT EXISTS (SELECT * FROM sys.schemas s WHERE s.name='group7')
EXEC ('CREATE SCHEMA [group7]');
GO

-- ************************************** [Adress]
IF NOT EXISTS (SELECT * FROM sys.tables t WHERE t.name='Prepayment' AND t.schema_id IN ( SELECT schema_id  FROM sys.schemas s WHERE s.name='group7'))
CREATE TABLE [group7].[Prepayment]
(
 [prepaymentID]   int  IDENTITY(1,1) PRIMARY KEY,
 [tenantID]   int NOT NULL ,
 [amount]     money NOT NULL ,
 [date]       date NOT NULL ,

 CONSTRAINT [FK_15] FOREIGN KEY ([tenantID]) REFERENCES [group7].[Tenant]([tenantID])
);
GO