-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [Property]
CREATE TABLE [Property]
(
 [propertyID] int NOT NULL ,
 [nrUnits]    int NOT NULL ,
 [adressID]   int NOT NULL ,
 [ownerID]    int NOT NULL ,
 [managerID]  int NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([propertyID] ASC),
 CONSTRAINT [FK_1] FOREIGN KEY ([managerID])  REFERENCES [Manager]([managerID]),
 CONSTRAINT [FK_2] FOREIGN KEY ([ownerID])  REFERENCES [Owner]([ownerID]),
 CONSTRAINT [FK_3] FOREIGN KEY ([adressID])  REFERENCES [Adress]([adressID])
);
GO


CREATE NONCLUSTERED INDEX [FK_2] ON [Property] 
 (
  [managerID] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_3] ON [Property] 
 (
  [ownerID] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_4] ON [Property] 
 (
  [adressID] ASC
 )

GO
