-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


IF NOT EXISTS (SELECT * FROM sys.schemas s WHERE s.name='group7')
EXEC ('CREATE SCHEMA [group7]');
GO

-- ************************************** [scsPosition]
IF NOT EXISTS (SELECT * FROM sys.tables t WHERE t.name='scsPosition' AND t.schema_id IN ( SELECT schema_id  FROM sys.schemas s WHERE s.name='group7'))
CREATE TABLE [group7].[scsPosition]
(
 [scsPositionID] int NOT NULL ,
 [amount]        int NOT NULL ,
 [scsID]         int NOT NULL ,
 [positionID]    int NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([scsPositionID] ASC),
 CONSTRAINT [FK_11] FOREIGN KEY ([positionID])  REFERENCES [Position]([positionID]),
 CONSTRAINT [FK_14_1] FOREIGN KEY ([scsID])  REFERENCES [SCS]([scsID])
);
GO


CREATE NONCLUSTERED INDEX [FK_2] ON [scsPosition] 
 (
  [positionID] ASC
 )

GO

CREATE NONCLUSTERED INDEX [FK_3] ON [scsPosition] 
 (
  [scsID] ASC
 )

GO
