-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [SCS]
CREATE TABLE [SCS]
(
 [scsID]         int NOT NULL ,
 [startInterval] datetime NOT NULL ,
 [tenantID]      int NOT NULL ,
 [endInterval]   datetime NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([scsID] ASC),
 CONSTRAINT [FK_9] FOREIGN KEY ([tenantID])  REFERENCES [Tenant]([tenantID])
);
GO


CREATE NONCLUSTERED INDEX [FK_2] ON [SCS] 
 (
  [tenantID] ASC
 )

GO
