-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v17 by b11shem06@gmail.com *******


IF NOT EXISTS (SELECT *
FROM sys.schemas s
WHERE s.name='group7')
EXEC ('CREATE SCHEMA [group7]');
GO


-- ************************************** [Transaction]
CREATE TABLE [group7].[Transaction]
(
    [transactionID]
        int IDENTITY(1,1) PRIMARY KEY,
    [postingDate] date NULL ,
    [valutaDate] date NULL ,
    [postingText] varchar(64) NULL ,
    [usage] varchar(64) NULL ,
    [payer] varchar(64) NULL ,
    [amount] money NULL ,
)


GO
