-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [Transaction]
CREATE TABLE [Transaction]
(
 [transactionID] int NOT NULL ,
 [line]           NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([transactionID] ASC)
);
GO
