-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v24 by b11shem06@gmail.com *******


IF NOT EXISTS (SELECT *
FROM sys.schemas s
WHERE s.name='group7')
EXEC ('CREATE SCHEMA [group7]');
GO
-- ************************************** [TransactionMapping]

CREATE TABLE [group7].[TransactionMapping]
(
    [mappingID] int IDENTITY(1,1) PRIMARY KEY ,
    [transactionPattern] varchar(50) NOT NULL ,
    [positionID] int NOT NULL ,


    CONSTRAINT [FK_18] FOREIGN KEY ([positionID])  REFERENCES [group7].[Position]([positionID])
);
GO
