-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ******* Generated by SqlDBM: model, v10 by b11shem06@gmail.com *******


-- ************************************** [Unit]
CREATE TABLE [Unit]
(
 [unitID]       int NOT NULL ,
 [squareMeters] int NOT NULL ,
 [propertyID]   int NOT NULL ,
 [nrRooms]      int NOT NULL ,


 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([unitID] ASC),
 CONSTRAINT [FK_8] FOREIGN KEY ([propertyID])  REFERENCES [Property]([propertyID])
);
GO


CREATE NONCLUSTERED INDEX [FK_2] ON [Unit] 
 (
  [propertyID] ASC
 )

GO
